server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.150.135:18848
    gateway:
      routes:
        - id: user-route
          uri: lb://service-user
          order: 1
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true