spring:
  datasource:
    url: localhost:3306/erp
    username: root
    password: 0408
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      port: 6379
      password: 0408

minio:
  endpoint: http://47.99.150.135:9000
  bucketName: mini-erp
  accessKey: minioadmin
  secretKey: minioadmin